### ISSUE TITLE
service name as parameter

### ISSUE THREAD

**Issue by lucamaf** [3scale/3scale-cli#55]
being able to define the service name upon creation from swagger definition instead of using a random name

**Comment by picsoung** [comment]
you can already provide a service name as explained here: https://github.com/3scale/3scale-cli/blob/master/docs/services.md

`3scale-cli services create --serviceName <service_name>`

otherwise, we use the name found in the swagger definition and add a random part to make sure that it does not collide with an existing service.

**Comment by lucamaf** [comment]
but there is no way of doing that directly in the import command correct?

**Comment by picsoung** [comment]
so far no.

Flow should be:

1. create a new service, get its ID
2. import spec into newly created service
