### ISSUE TITLE
System name mismatch

### ISSUE THREAD

**Issue by kasriniv** [3scale/3scale-cli#67]
3scale-cli import from swagger creates a system name say 'Customer30'.
However 3scale-cli activedocs create, creates a system name that is different say 'Customer59'.
These system names, i believe, have to be the same for the Developer portal catalog to work.
Can this be fixed please so that activedocs asks for userinput on systemname- if there is an existing system name to use.
Thanks!

**Comment by mayorova** [comment]
@kasriniv It looks like you can use `-s` / `--systemName` parameter to specify the desired system name when uploading the spec (see https://github.com/3scale/3scale-cli/blob/master/docs/create-activedocs.md#create-new-activedocs).

Otherwise (if the parameter not specified) it's using `api.info.title` from the spec + a random number.

**Comment by kasriniv** [comment]
Thanks @mayorova. Just checked that creating an active doc with -s <systemname> works fine. Closing this for now.
